<div class="container">
    <div class="form-box">
        <h2>Creer un Compte</h2>

        <form action="index.php?route=login" method="POST">

            <div>
                <label for="username">Nom d'Utilisateur</label>
                <input type="text" name="username" id="username" required placeholder="Exemple: Alice Dupont">
            </div>

            <div>
                <label for="email">Adresse E-mail</label>
                <input type="email" name="email" id="email" required placeholder="vous@exemple.com">
            </div>

            <div>
                <label for="password">Mot de Passe</label>
                <input type="password" name="password" id="password" required>
            </div>

            <div>
                <button type="submit">S'inscrire</button>
            </div>
        </form>

        <p>
            Deja un compte ?
            <a href="index.php?route=login">Se connecter ici</a>
        </p>
    </div>
</div>
